version: '3.8'  # Specify your Docker Compose version

services:
  app-1:
    image: auth_service
    build:
      context: .  # Build context if you have a Dockerfile
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: db
      PGPORT: 5432
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ADMIN_ACCESS_TOKEN: ${ADMIN_ACCESS_TOKEN}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "52463:3000"  # Map port 3000 of app-1 to 52463 on host

  app-2:
    image: auth_service
    build:
      context: .  # Build context if you have a Dockerfile
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: db
      PGPORT: 5432
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ADMIN_ACCESS_TOKEN: ${ADMIN_ACCESS_TOKEN}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "52494:3000"  # Map port 3000 of app-2 to 52494 on host

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    ports:
      - "3333:80"  # Expose Nginx on port 3333
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx config
    depends_on:
      - app-1      # Ensure Nginx starts after app-1
      - app-2      # Ensure Nginx starts after app-2
   
  redis-1:
    image: redis:latest
    ports:
      - "6388:6388"  # Map port 6379 of redis-1 to port 6379 on the host

  redis-2:
    image: redis:latest
    ports:
      - "6389:6389"  # Map port 6379 of redis-2 to port 6380 on the host

  redis-3:
    image: redis:latest
    ports:
      - "6390:6390"  # Map port 6379 of redis-3 to port 6381 on the host

  redis-4:
    image: redis:latest
    ports:
      - "6391:6391"  # Map port 6379 of redis-4 to port 6382 on the host

  redis-5:
    image: redis:latest
    ports:
      - "6393:6393"  # Map port 6379 of redis-5 to port 6383 on the host

  redis-6:
    image: redis:latest
    ports:
      - "6392:6392"  # Map port 6379 of redis-6 to port 6384 on the host

      